# Generated by Django 6.0.3 on 2026-05-27 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_invoice_user_complete_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('ecocash', 'EcoCash'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_verified'], name='invoice_verified_idx'),
        ),
    ]
