# Generated by Django 6.0.3 on 2026-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_summary_es_newsandevents_summary_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st Quarter', '1st Quarter'), ('2nd Quarter', '2nd Quarter'), ('3rd Quarter', '3rd Quarter'), ('4th Quarter', '4th Quarter')], max_length=12),
        ),
    ]
