# Generated by Django 6.0.3 on 2026-04-12 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_newsandevents_summary_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('F1', 'Form 1'), ('F2', 'Form 2'), ('F3', 'Form 3'), ('F4', 'Form 4'), ('F5', 'Form 5')], max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='upload_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_current_session',
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3'), ('T4', 'Term 4')], max_length=2)),
                ('is_current', models.BooleanField(default=False)),
                ('next_begins', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
