# Generated by Django 6.0.3 on 2026-04-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subject_class_assigned_subject_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubjectassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classsubjectassignment',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='classsubjectassignment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classsubjectassignment',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ClassSubjectAssignment',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
