# Generated by Django 6.0.3 on 2026-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_school_alter_schoolclass_name_alter_session_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
