# Generated by Django 6.0.3 on 2026-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_schoolclass_name_alter_session_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], default='Q1', max_length=2),
        ),
        migrations.AddField(
            model_name='school',
            name='last_payment_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='next_payment_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='suspended_reason',
            field=models.TextField(blank=True),
        ),
    ]
