# Generated by Django 6.0.3 on 2026-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_school_current_quarter_school_last_payment_on_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'level', 'name')},
        ),
    ]
