# Generated by Django 6.0.3 on 2026-05-26 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parent_parent_student_idx_and_more'),
        ('core', '0016_alter_session_session'),
        ('course', '0010_alter_subject_code_alter_subject_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', '-date', 'status'], name='att_school_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'school_class', 'date'], name='att_school_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'starts_on', 'status'], name='exam_school_start_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'school_class'], name='exam_school_class_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['fee', '-paid_on'], name='payment_fee_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['received_by', '-paid_on'], name='payment_receiver_idx'),
        ),
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['school', 'status', 'subject'], name='mark_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['school', 'student'], name='mark_school_student_idx'),
        ),
        migrations.AddIndex(
            model_name='newsandevents',
            index=models.Index(fields=['school', '-updated_at'], name='news_school_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='newsandevents',
            index=models.Index(fields=['school', 'posted_as'], name='news_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['status', 'is_active'], name='school_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['next_payment_due_on'], name='school_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'level', 'is_active'], name='class_school_level_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['school', 'status', 'due_date'], name='fee_school_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['school', 'student'], name='fee_school_student_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['school', 'session', 'term'], name='fee_school_period_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['school', 'is_current'], name='session_school_current_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school', 'is_current'], name='term_school_current_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school', 'session'], name='term_school_session_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'school_class', 'day'], name='time_school_class_day_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'teacher', 'day'], name='time_school_teacher_idx'),
        ),
    ]
