# Generated by Django 6.0.3 on 2026-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attendancerecord_att_school_date_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Unlimited (One-Time Payment)'),
        ),
        migrations.AddField(
            model_name='school',
            name='max_students',
            field=models.PositiveIntegerField(default=100, verbose_name='Max Students'),
        ),
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise'), ('unlimited', 'Unlimited (One-Time)')], default='starter', max_length=20),
        ),
    ]
