# Generated by Django 6.0.3 on 2026-05-27 19:33
# FIXED: allow null, clean orphaned data, then optionally make non-null later

import django.db.models.deletion
from django.db import migrations, models

def fix_orphaned_schools(apps, schema_editor):
    ActivityLog = apps.get_model('core', 'ActivityLog')
    School = apps.get_model('core', 'School')
    valid_school_ids = set(School.objects.values_list('id', flat=True))
    # If any activity log has a school_id that does not exist, set it to NULL
    ActivityLog.objects.exclude(school_id__in=valid_school_ids).update(school_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_school_is_unlimited_school_max_students_and_more'),
    ]

    operations = [
        # Step 1: Add the school field as nullable (so existing rows can have NULL)
        migrations.AddField(
            model_name='activitylog',
            name='school',
            field=models.ForeignKey(
                null=True,  # allow NULL temporarily
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='activity_logs',
                to='core.school'
            ),
        ),
        # Step 2: Clean up any invalid school_id values (set to NULL)
        migrations.RunPython(fix_orphaned_schools),
        # Step 3: Add the index (this works fine with NULLs)
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['school', '-created_at'], name='core_activi_school__38ef9f_idx'),
        ),
        # (Optional) If you want the field to be non‑nullable in the future,
        # create a separate migration after ensuring all rows have a valid school.
    ]