# Generated by Django 6.0.3 on 2026-05-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_activitylog_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.school'),
        ),
    ]
