# Generated by Django 6.0.3 on 2026-05-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_activitylog_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('F1', 'Form 1'), ('F2', 'Form 2'), ('F3', 'Form 3'), ('F4', 'Form 4'), ('F5', 'Form 5'), ('F6', 'Form 6')], default='F1', max_length=2),
        ),
    ]
