# Generated by Django 6.0.3 on 2026-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_schoolclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('parents', 'Parents Only'), ('students', 'Students Only'), ('teachers', 'Teachers Only')], default='all', max_length=20),
        ),
        migrations.AddIndex(
            model_name='newsandevents',
            index=models.Index(fields=['school', 'target_audience'], name='news_school_target_idx'),
        ),
    ]
