# Generated by Django 6.0.3 on 2026-04-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_classsubjectassignment_unique_together_and_more'),
        ('course', '0006_remove_course_program_remove_course_level_and_more'),
        ('quiz', '0007_alter_choice_options_alter_essayquestion_options_and_more'),
        ('result', '0004_remove_result_cgpa_remove_result_gpa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='course',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='course',
            new_name='subject',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Subject',
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('subjects', models.ManyToManyField(related_name='allocated_subjects', to='course.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseAllocation',
        ),
    ]
