# Generated by Django 6.0.3 on 2026-05-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_school_alter_schoolclass_name_alter_session_session_and_more'),
        ('course', '0008_remove_subject_credit_remove_subject_is_elective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
