# Generated by Django 6.0.3 on 2026-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schoolclass_unique_together_and_more'),
        ('course', '0009_subject_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'class_assigned', 'code')},
        ),
    ]
