# Generated by Django 6.0.3 on 2026-05-26 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attendancerecord_att_school_date_status_idx_and_more'),
        ('course', '0010_alter_subject_code_alter_subject_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'class_assigned'], name='subject_school_class_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'teacher'], name='subject_school_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'code'], name='subject_school_code_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectallocation',
            index=models.Index(fields=['teacher', 'session'], name='alloc_teacher_session_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['subject', '-upload_time'], name='upload_subject_time_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadvideo',
            index=models.Index(fields=['subject', '-timestamp'], name='video_subject_time_idx'),
        ),
    ]
