# Generated by Django 6.0.3 on 2026-05-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_subject_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
    ]
