# Generated by Django 6.0.3 on 2026-06-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_parent_options_and_more'),
        ('course', '0015_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_electable',
            field=models.BooleanField(default=False, help_text='If checked, students can optionally add this subject to their class subjects', verbose_name='Electable Subject'),
        ),
        migrations.CreateModel(
            name='StudentElectedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elected_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elected_subjects', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elected_by_students', to='course.subject')),
            ],
            options={
                'ordering': ['subject__title'],
                'indexes': [models.Index(fields=['student', 'subject'], name='elected_student_subject_idx')],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
