# Generated by Codex on 2026-06-05

import course.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_subject_is_electable_studentelectedsubject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                storage=course.storage.course_file_storage,
                upload_to="course_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7zip",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="video",
            field=models.FileField(
                storage=course.storage.course_video_storage,
                upload_to="course_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                    )
                ],
            ),
        ),
    ]
