# Generated by Codex on 2026-05-12

from django.db import migrations, models
from django.db.models import Q


def remove_duplicate_completed_sittings(apps, schema_editor):
    Sitting = apps.get_model("quiz", "Sitting")

    duplicate_groups = (
        Sitting.objects.filter(complete=True)
        .values("user_id", "quiz_id", "course_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    for group in duplicate_groups:
        sittings = Sitting.objects.filter(
            complete=True,
            user_id=group["user_id"],
            quiz_id=group["quiz_id"],
            course_id=group["course_id"],
        ).order_by("-end", "-id")
        keep = sittings.first()
        sittings.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_choice_options_alter_essayquestion_options_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_completed_sittings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="sitting",
            constraint=models.UniqueConstraint(
                fields=("user", "quiz", "course"),
                condition=Q(complete=True),
                name="unique_completed_sitting_per_quiz_course_user",
            ),
        ),
    ]
