# Generated by Django 6.0.3 on 2026-05-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_unique_completed_sittings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sitting',
            name='unique_completed_sitting_per_quiz_course_user',
        ),
    ]
