# Generated by Django 6.0.3 on 2026-05-26 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_sitting_unique_completed_sitting_per_quiz_course_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, help_text='Marks available for this question.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Marks'),
        ),
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_marks', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_question_grades', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting_grades', to='quiz.question')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_grades', to='quiz.sitting')),
            ],
            options={
                'verbose_name': 'Question Grade',
                'verbose_name_plural': 'Question Grades',
                'unique_together': {('sitting', 'question')},
            },
        ),
    ]
