# Generated by Django 6.0.3 on 2026-05-26 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_subject_subject_school_class_idx_and_more'),
        ('quiz', '0010_question_marks_questiongrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'category', 'draft'], name='quiz_course_category_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', '-timestamp'], name='quiz_course_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sitting',
            index=models.Index(fields=['user', 'quiz', 'course', 'complete'], name='sitting_user_quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='sitting',
            index=models.Index(fields=['course', 'complete'], name='sitting_course_complete_idx'),
        ),
        migrations.AddIndex(
            model_name='sitting',
            index=models.Index(fields=['quiz', 'complete'], name='sitting_quiz_complete_idx'),
        ),
    ]
