# Generated by Django 6.0.3 on 2026-06-01 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_parent_options_and_more'),
        ('quiz', '0011_quiz_quiz_course_category_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='test_date',
            field=models.DateField(blank=True, help_text='Date for a physical test or scheduled assessment.', null=True, verbose_name='Test Date'),
        ),
        migrations.CreateModel(
            name='TestMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_test_marks', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(limit_choices_to={'category': 'exam'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_marks', to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['quiz', 'student'], name='testmark_quiz_student_idx')],
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
