# Generated by Django 6.0.3 on 2026-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthead',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dep_head',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('F1', 'Form 1 (Year 1)'), ('F2', 'Form 2 (Year 2)'), ('F3', 'Form 3 (Year 3)'), ('F4', 'Form 4 (Year 4)'), ('F5', 'Form 5 (Year 5)')], max_length=25, null=True),
        ),
    ]
