# Generated by Django 6.0.3 on 2026-04-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_departmenthead_department_and_more'),
        ('core', '0010_alter_classsubjectassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolclass'),
        ),
    ]
