# Generated by Django 6.0.3 on 2026-05-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=160)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'is_lecturer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'user__username'),
            },
        ),
    ]
