# Generated by Django 6.0.3 on 2026-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_school'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_alter_session_session'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['student'], name='parent_student_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_class', 'level'], name='student_class_level_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'is_superuser'], name='acct_user_school_admin_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'is_lecturer'], name='acct_user_school_lec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'is_student'], name='acct_user_school_stu_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'is_parent'], name='acct_user_school_par_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='acct_user_email_idx'),
        ),
    ]
