# Generated by Django 6.0.3 on 2026-06-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parent_parent_student_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ('-user__date_joined',), 'verbose_name_plural': 'Parents'},
        ),
        migrations.RemoveIndex(
            model_name='parent',
            name='parent_student_idx',
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['user'], name='parent_user_idx'),
        ),
    ]
